<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "exposition_ag_nm"
 *
 * Auto generated by Extension Builder 2018-07-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'exposition_AG_NM',
    'description' => 'Projet DAWIN expositon',
    'category' => 'plugin',
    'author' => 'Gonzalez Alexandre, Marcilloux Nicolas',
    'author_email' => 'alexandregonzalez33470@gmail.com, nicolas.marcilloux@etu.u-bordeaux.fr',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
